# Generated by Django 2.2.6 on 2021-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitewall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
