# Generated by Django 2.2.6 on 2021-12-25 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character2',
        ),
        migrations.DeleteModel(
            name='Character3',
        ),
        migrations.DeleteModel(
            name='Character4',
        ),
    ]
